name: "Build and test"

on:
  push:
    branches: [main]
  pull_request: {}

jobs:
  build:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go 1.18
        uses: actions/setup-go@v3
        with:
          go-version: '1.18'

      - name: Check Go source files are properly formatted
        run: "! go fmt ./... | grep . || { echo 'Go not formatted'; exit 1; }"

      - name: Build program
        run: go build ./...

      - name: Run tests
        run: go test ./...